version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Kolkata
      NODE_ENV: development
      PORT: 3000
      # Auth
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      # Twilio
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      # Database
      MONGODB_URI: mongodb://root:example@mongo:27017/uber-rapido?authSource=admin
      # New Ride Features
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      PREMIUM_RATE_PER_KM: ${PREMIUM_RATE_PER_KM}
      TAXI_RATE_PER_KM: ${TAXI_RATE_PER_KM}
      ELECTRIC_RATE_PER_KM: ${ELECTRIC_RATE_PER_KM}
      MINI_RATE_PER_KM: ${MINI_RATE_PER_KM}
      # Redis
      REDIS_URL: redis://redis:6379
      # Payment
      # RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      # RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon src/app.js  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Kolkata
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: uber-rapido
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh -u root -p example --quiet || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge